name: CI/CD Pipeline

on:
  workflow_run:
    workflows: ["Authenticate with GCP"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Lint Terraform code
        run: |
          terraform fmt -check
          terraform init
          tflint --init
          tflint

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Terraform Validate
        run: |
          terraform init
          terraform validate

  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Terraform Plan
        run: |
          terraform init
          terraform plan

  apply:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve

  deploy:
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to Cloud Storage
        run: |
          gsutil cp -r frontend/* gs://${{ secrets.GCS_BUCKET }}/
      
      - name: Run post-deployment tests
        run: |
          curl https://your-site-url.com
